CREATE DATABASE IF NOT EXISTS ContactsDB;
USE ContactsDB;

CREATE TABLE IF NOT EXISTS Contacts (
  ContactId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FullName VARCHAR(100) NOT NULL,
  Email VARCHAR(150),
  Phone VARCHAR(50),
  Address VARCHAR(250),
  Notes TEXT,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
select * from Contacts;
